import { invoke } from "@tauri-apps/api/core";

/** `mcp_server::McpServerStatusDto`: the switch, the listener, and the
 * ready-to-copy client configuration generated by the backend. */
export type McpServerStatusDto = {
  supported: boolean;
  enabled: boolean;
  running: boolean;
  error: string | null;
  binaryPath: string;
  binaryFound: boolean;
  claudeCodeCommand: string;
  claudeCodeConfig: string;
  cursorConfig: string;
};

export async function mcpServerStatus(): Promise<McpServerStatusDto> {
  return invoke<McpServerStatusDto>("mcp_server_status");
}

export async function mcpServerSetEnabled(enabled: boolean): Promise<McpServerStatusDto> {
  return invoke<McpServerStatusDto>("mcp_server_set_enabled", {
    request: { enabled },
  });
}
