//! Clipboard monitoring with password-manager concealment detection.

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};

/// Retrieves the general clipboard text if the change count has advanced
/// since the previous inspection, unless the pasteboard declares concealed or
/// transient types used by password managers.
pub fn clipboard_text_if_changed(last_change_count: &mut isize) -> Option<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let current_count = pasteboard.changeCount();

    if current_count == *last_change_count {
        return None;
    }
    *last_change_count = current_count;

    // Check for concealed or transient markers (1Password, Bitwarden, KeePass, Keychain, etc.)
    if let Some(types) = pasteboard.types() {
        for t in &types {
            let t_str = t.to_string();
            if t_str == "org.nspasteboard.ConcealedType"
                || t_str == "org.nspasteboard.TransientType"
                || t_str == "org.nspasteboard.AutoGeneratedType"
                || t_str.starts_with("com.agilebits.onepassword")
            {
                return None;
            }
        }
    }

    let val = unsafe { pasteboard.stringForType(NSPasteboardTypeString) };
    val.map(|s| s.to_string()).filter(|s| !s.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_clipboard_change_tracking() {
        let mut count = -1;
        // First check may or may not return text, but will update count
        let _ = clipboard_text_if_changed(&mut count);
        assert!(count >= 0);

        // Immediate second check should return None (no change)
        let second = clipboard_text_if_changed(&mut count);
        assert_eq!(second, None);
    }
}
