//! Day intelligence: from captured activity to hour reports, the day's
//! workstreams, and the day summary with its standup, generated by the
//! user's activity provider and delivered on schedule with notifications.
//! Contract, schema, and read API: `docs/day-intelligence.md`.
//!
//! Layout: `distill` + `embedder` (local text reduction, no network but the
//! one-time model download), `hour`, `workstreams`, `summary` (prompts in and
//! answers out, pure), `prompts`, `schedule` (time decisions, pure),
//! `notify` (notice queue and quiet hours), `sources` (meetings and notes,
//! coding-agent blocks), `db` (tables and read API), `pipeline`
//! (orchestration over injected dependencies), and this file (Tauri state,
//! background loop, commands).

pub mod db;
pub mod distill;
pub mod embedder;
pub mod hour;
pub mod notify;
pub mod pipeline;
pub mod prompts;
pub mod schedule;
pub mod sources;
pub mod summary;
pub mod workstreams;

#[cfg(test)]
mod pipeline_tests;
#[cfg(test)]
#[path = "red_tests.rs"]
mod red_tests;
#[cfg(test)]
mod test_support;

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration as StdDuration, Instant};

use chrono::{Duration, NaiveDate, Utc};
use serde::Deserialize;
use tauri::{AppHandle, Emitter, Manager, State};

use crate::activity::schedule::CaptureState;
use crate::activity::store::ActivityStore;
use crate::activity::timeline::{self, Availability, StoreAccess};
use crate::activity::ActivityState;
use crate::domain::types::AppError;
use crate::llm::registry::ProviderRef;
use crate::llm::LlmError;
use embedder::{EmbedderStatus, LocalEmbedder};
use notify::{NoticeKind, NoticeQueue};
use pipeline::{
    ActivityProvider, DayIntelligenceDto, Deps, ProviderState, ReadContext, ScheduledRun,
    SummaryRun,
};
use schedule::{day_key, local_day, parse_day, LocalZone, SystemZone};
use sources::AppSources;
use summary::DayPanelsDto;

/// Emitted when a day's reports, workstreams, or summary changed, or a run
/// started or ended. Payload `{ day, running }`.
pub const DAY_INTELLIGENCE_EVENT: &str = "clovy://day-intelligence";
const TICK: StdDuration = StdDuration::from_secs(60);
const PRUNE_EVERY: StdDuration = StdDuration::from_secs(3600);

/// Tauri-managed state, present on every platform (commands answer
/// `unsupported` without activity capture).
pub struct DayIntelligenceState {
    embedder: Arc<LocalEmbedder>,
    notices: Mutex<NoticeQueue>,
    /// One pipeline run at a time (scheduler or "Generate").
    run: tokio::sync::Mutex<()>,
    running: AtomicBool,
    wake: tokio::sync::Notify,
    /// The capture failure already notified, so a repeated state is quiet.
    capture_failure: Mutex<Option<String>>,
}

fn lock<T>(mutex: &Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    mutex
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DayRequest {
    /// Local day, "YYYY-MM-DD".
    pub day: String,
}

/// Whether activity generation can run: an activity provider with JSON
/// schema support is chosen.
pub fn provider_state() -> ProviderState {
    let registry = crate::llm::registry();
    let provider = registry.usage.activity.clone();
    if matches!(provider, ProviderRef::None | ProviderRef::Clovy) {
        return ProviderState::Missing;
    }
    if registry
        .level_of(&provider)
        .is_some_and(crate::llm::StructuredOutputLevel::supports_json_schema)
    {
        ProviderState::Ready
    } else {
        ProviderState::Insufficient
    }
}

/// Registers the state and, where activity capture runs, the background
/// loop. Call after `activity::setup`.
pub fn setup(app: &mut tauri::App) {
    let models = crate::app_paths::app_data_dir(app.handle())
        .map(|dir| dir.join("models"))
        .unwrap_or_default();
    app.manage(DayIntelligenceState {
        embedder: Arc::new(LocalEmbedder::new(&models)),
        notices: Mutex::new(NoticeQueue::default()),
        run: tokio::sync::Mutex::new(()),
        running: AtomicBool::new(false),
        wake: tokio::sync::Notify::new(),
        capture_failure: Mutex::new(None),
    });
    if app.state::<ActivityState>().runtime().is_some() {
        start(app.handle().clone());
    }
}

fn emit(app: &AppHandle, day: &str, running: bool) {
    let _ = app.emit(
        DAY_INTELLIGENCE_EVENT,
        serde_json::json!({ "day": day, "running": running }),
    );
}

fn start(app: AppHandle) {
    tauri::async_runtime::spawn(async move {
        let mut last_prune: Option<Instant> = None;
        loop {
            tick(&app, &mut last_prune).await;
            let state = app.state::<DayIntelligenceState>();
            let until_notice = lock(&state.notices)
                .next_delivery()
                .and_then(|at| (at - Utc::now()).to_std().ok())
                .unwrap_or(TICK);
            tokio::select! {
                _ = tokio::time::sleep(until_notice.min(TICK)) => {}
                _ = state.wake.notified() => {}
            }
        }
    });
}

fn deliver_notices(
    app: &AppHandle,
    state: &DayIntelligenceState,
    settings: &crate::activity::settings::ActivitySettings,
) {
    let due = lock(&state.notices).take_due(Utc::now(), &SystemZone, &settings.notifications);
    let locale = crate::interface_locale::current();
    for notice in due {
        let (title, body, snooze_label) = notify::copy(&notice, locale);
        let result = crate::notifications::send_today_notification(
            app,
            &crate::notifications::TodayNotification {
                title,
                body,
                day: notice.day.clone(),
                kind: notice.kind.as_str().to_string(),
                snooze_label,
            },
        );
        if let Err(error) = result {
            tracing::warn!(%error, "activity notification failed");
        }
    }
}

fn raise(app: &AppHandle, kind: NoticeKind, day: String, detail: Option<String>) {
    let Some(state) = app.try_state::<DayIntelligenceState>() else {
        return;
    };
    let Some(runtime) = app
        .state::<ActivityState>()
        .runtime()
        .map(|runtime| runtime.shared().settings())
    else {
        return;
    };
    lock(&state.notices).raise(
        kind,
        day,
        detail,
        Utc::now(),
        &SystemZone,
        &runtime.notifications,
    );
    state.wake.notify_one();
}

/// Called with every capture state change: an error or a lost key raises a
/// failure notification once per distinct failure.
pub fn on_capture_state(app: &AppHandle, capture: &CaptureState) {
    let Some(state) = app.try_state::<DayIntelligenceState>() else {
        return;
    };
    let failure = match capture {
        CaptureState::KeyMissing => {
            Some("The activity database key is missing from the Keychain.".to_string())
        }
        CaptureState::Error { message } => Some(message.clone()),
        _ => None,
    };
    let changed = {
        let mut last = lock(&state.capture_failure);
        let changed = failure.is_some() && *last != failure;
        last.clone_from(&failure);
        changed
    };
    if changed {
        let day = day_key(local_day(&SystemZone, Utc::now()));
        raise(app, NoticeKind::CaptureFailed, day, failure);
    }
}

/// The notification's "Snooze 1h" button.
pub fn snooze_notice(app: &AppHandle, kind: &str, day: &str) {
    let (Some(state), Some(kind)) = (
        app.try_state::<DayIntelligenceState>(),
        NoticeKind::parse(kind),
    ) else {
        return;
    };
    lock(&state.notices).snooze(kind, day.to_string(), None, Utc::now());
    state.wake.notify_one();
}

async fn tick(app: &AppHandle, last_prune: &mut Option<Instant>) {
    let state = app.state::<DayIntelligenceState>();
    let activity = app.state::<ActivityState>();
    let Some(runtime) = activity.runtime() else {
        return;
    };
    let settings = runtime.shared().settings();
    deliver_notices(app, &state, &settings);
    if !settings.enabled {
        return;
    }
    let Some(store) = runtime.shared().store() else {
        return;
    };
    let zone = SystemZone;
    let now = Utc::now();
    if last_prune.map_or(true, |at| at.elapsed() >= PRUNE_EVERY) {
        *last_prune = Some(Instant::now());
        if let Err(error) = pipeline::prune(&store, &settings, &zone, now).await {
            tracing::warn!(%error, "day intelligence retention failed");
        }
    }
    // Inactive without an activity provider: nothing is generated or downloaded.
    if provider_state() != ProviderState::Ready {
        return;
    }
    if state.embedder.status() == EmbedderStatus::Absent {
        let embedder = Arc::clone(&state.embedder);
        tauri::async_runtime::spawn(async move { embedder.ensure_ready().await });
    }
    let Ok(_guard) = state.run.try_lock() else {
        return;
    };
    let today = local_day(&zone, now);
    let sources = AppSources { app: app.clone() };
    let deps = Deps {
        store: &store,
        settings: &settings,
        generator: &ActivityProvider,
        embedder: state.embedder.as_ref(),
        sources: &sources,
        zone: &zone,
        locale: crate::interface_locale::current(),
        now,
    };
    let yesterday = today - Duration::days(1);
    for day in [yesterday, today] {
        match pipeline::catch_up_day(&deps, day, false).await {
            Ok(result) if result.reported + result.folded > 0 => emit(app, &day_key(day), false),
            Ok(_) => {}
            Err(error) => tracing::warn!(%error, "day intelligence catch-up failed"),
        }
    }
    let mut records = Vec::with_capacity(2);
    for day in [yesterday, today] {
        match db::run_record(&store, &format!("auto:{}", day_key(day))).await {
            Ok(record) => records.push(record),
            Err(error) => {
                tracing::warn!(%error, "day summary run record unreadable");
                return;
            }
        }
    }
    let Some(day) = schedule::auto_summary_day(
        zone.local(now),
        &settings.day_summary.time,
        records[0].as_ref(),
        records[1].as_ref(),
        now,
    ) else {
        return;
    };
    let key = day_key(day);
    let started = || {
        state.running.store(true, Ordering::SeqCst);
        emit(app, &key, true);
    };
    let outcome = pipeline::run_scheduled_summary(&deps, day, &started).await;
    let generated = state.running.swap(false, Ordering::SeqCst);
    match outcome {
        Ok(ScheduledRun::Waiting(reason)) => {
            tracing::debug!(day = %key, %reason, "day summary waits for its inputs");
        }
        Ok(ScheduledRun::Generated(summary)) => {
            raise(
                app,
                NoticeKind::SummaryReady,
                key.clone(),
                Some(summary.headline),
            );
        }
        Ok(ScheduledRun::Empty) => {}
        Ok(ScheduledRun::Failed { message, first }) => {
            tracing::warn!(%message, "scheduled day summary failed");
            if first {
                raise(app, NoticeKind::SummaryFailed, key.clone(), Some(message));
            }
        }
        Err(error) => tracing::warn!(%error, "day summary run not recorded"),
    }
    if generated {
        emit(app, &key, false);
    }
}

fn parse_request_day(day: &str) -> Result<NaiveDate, AppError> {
    parse_day(day)
        .ok_or_else(|| AppError::new("day_intelligence_invalid_day", "`day` must be YYYY-MM-DD"))
}

fn empty_dto(
    availability: Availability,
    day: &str,
    state: &DayIntelligenceState,
    summary_time: String,
) -> DayIntelligenceDto {
    DayIntelligenceDto {
        availability,
        day: day.to_string(),
        provider: provider_state(),
        embedder: state.embedder.status(),
        running: state.running.load(Ordering::SeqCst),
        summary_time,
        summary: None,
        workstreams: Vec::new(),
        hour_reports: Vec::new(),
        panels: DayPanelsDto::default(),
    }
}

async fn read_dto(
    app: &AppHandle,
    state: &DayIntelligenceState,
    store: &ActivityStore,
    settings: &crate::activity::settings::ActivitySettings,
    day: NaiveDate,
) -> Result<DayIntelligenceDto, AppError> {
    let sources = AppSources { app: app.clone() };
    let context = ReadContext {
        store,
        settings,
        sources: &sources,
        zone: &SystemZone,
        now: Utc::now(),
    };
    let (summary, workstreams, hour_reports, panels) = pipeline::day_view(&context, day)
        .await
        .map_err(|error| AppError::new("day_intelligence_read_failed", error.to_string()))?;
    Ok(DayIntelligenceDto {
        availability: Availability::Ready,
        day: day_key(day),
        provider: provider_state(),
        embedder: state.embedder.status(),
        running: state.running.load(Ordering::SeqCst),
        summary_time: settings.day_summary.time.clone(),
        summary,
        workstreams,
        hour_reports,
        panels,
    })
}

/// The "Today" view's day intelligence: summary, workstreams, hour reports,
/// and panels computed from the data now.
#[tauri::command]
pub async fn day_intelligence_day(
    app: AppHandle,
    state: State<'_, DayIntelligenceState>,
    activity: State<'_, ActivityState>,
    request: DayRequest,
) -> Result<DayIntelligenceDto, AppError> {
    let day = parse_request_day(&request.day)?;
    let Some(runtime) = activity.runtime() else {
        return Ok(empty_dto(
            Availability::Unsupported,
            &request.day,
            &state,
            String::new(),
        ));
    };
    let settings = runtime.shared().settings();
    let store = match timeline::store_access(runtime).await {
        StoreAccess::Open(store) => store,
        StoreAccess::Empty => {
            return Ok(empty_dto(
                Availability::Ready,
                &request.day,
                &state,
                settings.day_summary.time,
            ))
        }
        StoreAccess::Unavailable(availability, _) => {
            return Ok(empty_dto(
                availability,
                &request.day,
                &state,
                settings.day_summary.time,
            ))
        }
    };
    read_dto(&app, &state, &store, &settings, day).await
}

/// "Generate summary": reports the day's pending hours (retrying failed ones
/// now) and writes the summary in the interface language.
#[tauri::command]
pub async fn day_intelligence_generate(
    app: AppHandle,
    state: State<'_, DayIntelligenceState>,
    activity: State<'_, ActivityState>,
    request: DayRequest,
) -> Result<DayIntelligenceDto, AppError> {
    let day = parse_request_day(&request.day)?;
    match provider_state() {
        ProviderState::Ready => {}
        ProviderState::Missing => return Err(LlmError::ActivityProviderMissing.into()),
        ProviderState::Insufficient => return Err(LlmError::StructuredOutputInsufficient.into()),
    }
    let runtime = activity.runtime().ok_or_else(|| {
        AppError::new(
            "activity_unsupported",
            "Activity capture is available on macOS only.",
        )
    })?;
    let settings = runtime.shared().settings();
    let StoreAccess::Open(store) = timeline::store_access(runtime).await else {
        return Err(AppError::new(
            "activity_database_closed",
            "The activity database is not open. Turn capture on first.",
        ));
    };
    if state.embedder.status() == EmbedderStatus::Absent {
        let embedder = Arc::clone(&state.embedder);
        tauri::async_runtime::spawn(async move { embedder.ensure_ready().await });
    }
    let _guard = state.run.lock().await;
    state.running.store(true, Ordering::SeqCst);
    emit(&app, &request.day, true);
    timeline::refresh_before_read(&app, &store).await;
    let sources = AppSources { app: app.clone() };
    let zone = SystemZone;
    let deps = Deps {
        store: &store,
        settings: &settings,
        generator: &ActivityProvider,
        embedder: state.embedder.as_ref(),
        sources: &sources,
        zone: &zone,
        locale: crate::interface_locale::current(),
        now: Utc::now(),
    };
    let result = match pipeline::summarize_on_demand(&deps, day).await {
        Ok(SummaryRun::Generated(_)) => Ok(()),
        Ok(SummaryRun::Empty) => Err(AppError::new(
            "day_summary_no_activity",
            "There is no activity to summarize for this day yet.",
        )),
        Ok(SummaryRun::Incomplete(reason)) => Err(AppError::new(
            "day_summary_incomplete",
            format!("The summary was not written because part of the day is not ready ({reason}). Try again in a few minutes."),
        )),
        Err(pipeline::PipelineError::Llm(error)) => Err(error.0.into()),
        Err(error) => Err(AppError::new("day_intelligence_failed", error.to_string())),
    };
    state.running.store(false, Ordering::SeqCst);
    emit(&app, &request.day, false);
    result?;
    read_dto(&app, &state, &store, &settings, day).await
}
